### ISSUE TITLE
bytom is not a constructor

### ISSUE THREAD

**Issue by dsky1990** [Bytom/node-sdk#1]
```
const bytom = require('bytom-sdk')

const client = new bytom(url, accessToken)
               ^
TypeError: bytom is not a constructor
    at Object.<anonymous> (/Users/dsky/bitcloud/bitcloud-wallet/address/btm.js:4:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by ZhitingLin** [comment]
Please what the document written

const bytom = require('bytom-sdk')
const url = 'http://localhost:9888'

// access token is required when client is not in same origin
// with the request bytom node
const accessToken = ''

const client = new bytom.Client(url, accessToken)
